
import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

const fontRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900"], 
});

import { Metadata } from "next";

export const metadata : Metadata = {
  title: "Bidding App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${fontRoboto.variable} antialiased`}
        >
        {children}
      </body>
    </html>
    </AuthProvider>
  );
}
